services:
  workflow-orchestrator:
    image:
      sagebionetworks/synapse-workflow-orchestrator:1.0
    volumes:
    - ${WES_SHARED_DIR_PROPERTY}:${WES_SHARED_DIR_PROPERTY}:rw
    environment:
    - WES_ENDPOINT=${WES_ENDPOINT}
    - WES_SHARED_DIR_PROPERTY=${WES_SHARED_DIR_PROPERTY}
    - SYNAPSE_USERNAME=${SYNAPSE_USERNAME}
    - SYNAPSE_PAT=${SYNAPSE_PAT}
    - WORKFLOW_OUTPUT_ROOT_ENTITY_ID=${WORKFLOW_OUTPUT_ROOT_ENTITY_ID}
    - EVALUATION_TEMPLATES=${EVALUATION_TEMPLATES}
    - NOTIFICATION_PRINCIPAL_ID=${NOTIFICATION_PRINCIPAL_ID}
    - SHARE_RESULTS_IMMEDIATELY=${SHARE_RESULTS_IMMEDIATELY}
    - DATA_UNLOCK_SYNAPSE_PRINCIPAL_ID=${DATA_UNLOCK_SYNAPSE_PRINCIPAL_ID}
    - MAX_CONCURRENT_WORKFLOWS=${MAX_CONCURRENT_WORKFLOWS}
    - SUBMITTER_NOTIFICATION_MASK=${SUBMITTER_NOTIFICATION_MASK}
    
  wes:
    image:
      sagebionetworks/synapse-workflow-orchestrator-wes:1.0
    volumes:
    - ${WES_SHARED_DIR_PROPERTY}:${WES_SHARED_DIR_PROPERTY}:ro
    ports:
    - 8082:8082
      
    
    